# Generated by Django 5.0.1 on 2024-02-08 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_size',
            field=models.CharField(choices=[('Small', 'small'), ('Medium', 'medium'), ('Large', 'large'), ('Extra large', 'extra_large')], default='Small', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='dog',
            unique_together={('owner', 'name')},
        ),
    ]
