# Generated by Django 5.0.1 on 2024-02-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_dog_size_alter_dog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_size',
            field=models.CharField(choices=[('Small', 'small'), ('Medium', 'medium'), ('Large', 'large'), ('Extra large', 'extra large')], default='Small', max_length=15),
        ),
    ]
