# Generated by Django 5.0.1 on 2024-02-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_dog_dog_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Male', max_length=15),
        ),
    ]
