# Generated by Django 5.0.1 on 2024-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_age',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
