# Generated by Django 5.0.1 on 2024-03-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_dog_age_dog_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_age',
            field=models.IntegerField(),
        ),
    ]
