# Generated by Django 5.0.1 on 2024-03-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_alter_dog_dog_age'),
        ('vaccination', '0004_vaccineuserparticipant_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='vaccines',
            field=models.ManyToManyField(through='vaccination.VaccineUserParticipant', to='vaccination.vaccine'),
        ),
    ]
