# Generated by Django 5.0.2 on 2024-02-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_alter_dog_dog_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
