# Generated by Django 5.0.1 on 2024-02-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venues',
            field=models.ManyToManyField(through='venue.VenueEventsParticipants', to='venue.venue'),
        ),
    ]
