# Generated by Django 5.0.1 on 2024-02-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AddField(
            model_name='event',
            name='venues',
            field=models.ManyToManyField(through='venue.VenueEventsParticipant', to='venue.venue'),
        ),
        migrations.DeleteModel(
            name='EventUserParticipant',
        ),
    ]
