# Generated by Django 5.0.3 on 2024-08-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0010_rename_petnames_petname'),
        ('events', '0002_remove_event_participants_event_venues_and_more'),
        ('venue', '0002_alter_venueeventsparticipants_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='PetEntertainment',
        ),
    ]
