# Generated by Django 5.0.1 on 2024-02-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_place', models.CharField(max_length=100)),
                ('venue_date', models.DateField(null=True)),
                ('events', models.ManyToManyField(to='events.event')),
            ],
        ),
    ]
