# Generated by Django 5.0.1 on 2024-02-15 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_place', models.CharField(max_length=100)),
                ('venue_date', models.DateField(null=True)),
                ('description', models.TextField(default='Please input the information for this event.')),
            ],
        ),
        migrations.CreateModel(
            name='VenueEventsParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue')),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='events',
            field=models.ManyToManyField(through='venue.VenueEventsParticipant', to='events.event'),
        ),
    ]
