# Generated by Django 5.0.1 on 2024-02-15 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_dog_gender'),
        ('events', '0002_event_venues'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venueeventsparticipants',
            unique_together={('venue', 'event')},
        ),
        migrations.CreateModel(
            name='DogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.CharField(blank=True, max_length=50)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
