# Generated by Django 5.0.1 on 2024-02-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_events'),
        ('events', '0002_event_venues'),
        ('venue', '0002_alter_venueeventsparticipants_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dogevent',
            unique_together={('dog', 'event')},
        ),
    ]
