# Generated by Django 5.0.1 on 2024-02-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_venue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(default='Please input the information for this event.'),
        ),
    ]
