# Generated by Django 5.0.1 on 2024-01-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vaccination_type', models.CharField(max_length=100)),
                ('vaccination_date', models.DateField(null=True)),
                ('description', models.TextField(default='Please input the information for this vaccine.')),
            ],
        ),
    ]
