# Generated by Django 5.0.1 on 2024-01-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='title',
            new_name='vaccination_title',
        ),
    ]
