# Generated by Django 5.0.1 on 2024-01-29 12:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_rename_title_vaccine_vaccination_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineUserParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccine')),
            ],
            options={
                'unique_together': {('participant', 'vaccine')},
            },
        ),
        migrations.AddField(
            model_name='vaccine',
            name='participants',
            field=models.ManyToManyField(through='vaccination.VaccineUserParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
