# Generated by Django 5.0.1 on 2024-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_vaccineuserparticipant_vaccine_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineuserparticipant',
            name='attendee',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
