# Generated by Django 5.0.1 on 2024-03-03 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_dog_vaccines'),
        ('vaccination', '0004_vaccineuserparticipant_attendee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccineuserparticipant',
            old_name='participant',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='vaccineuserparticipant',
            unique_together={('owner', 'vaccine')},
        ),
        migrations.AddField(
            model_name='vaccineuserparticipant',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.dog'),
        ),
    ]
