# Generated by Django 5.0.1 on 2024-03-03 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_dog_vaccines'),
        ('vaccination', '0005_rename_participant_vaccineuserparticipant_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineuserparticipant',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog'),
        ),
    ]
