# Generated by Django 5.0.4 on 2024-04-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_dog_vaccines'),
        ('vaccination', '0006_alter_vaccineuserparticipant_dog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vaccineuserparticipant',
            unique_together={('dog', 'vaccine')},
        ),
    ]
